name: Deploy Postman Test Runner

on:
  push:
    branches:
      - main  # Ğ·Ğ°Ğ¿ÑƒÑĞº Ğ¿Ñ€Ğ¸ Ğ¿ÑƒÑˆĞµ Ğ² main
  workflow_dispatch: # Ğ·Ğ°Ğ¿ÑƒÑĞº Ğ²Ñ€ÑƒÑ‡Ğ½ÑƒÑ Ğ¸Ğ· Actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ”‘ Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ğŸ›  Build Docker image
        run:  build -t xyedil/postman-test:latest .

      - name: ğŸ“¤ Push image to DockerHub
        run: docker push xyedil/postman-test:latest
